/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.bingo;

import javax.swing.JOptionPane;
import java.util.ArrayList;
import javax.swing.table.TableModel;

/**
 * Ventana de consultar cartón
 */
public class ConsultarCarton extends javax.swing.JFrame {

  private Bingo bingo;
  /**
   * Constructor de la clase ConsultarCarton.
   *
   * @param pBingo Objeto Bingo con los datos de la sesión actual.
   */
  public ConsultarCarton(Bingo pBingo) {
    initComponents();
    bingo = pBingo;
    tablaNumerosBingo.getTableHeader().setVisible(false);
    tablaNumerosBingo.setRowHeight((int) (tablaNumerosBingo.getWidth() / 5));
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    textoConsultarCarton = new javax.swing.JLabel();
    textoIdentificador = new javax.swing.JLabel();
    entradaIdentificador = new javax.swing.JTextField();
    botonRegresar = new javax.swing.JButton();
    botonMostrar = new javax.swing.JButton();
    textoNombreJugador = new javax.swing.JLabel();
    jScrollPane3 = new javax.swing.JScrollPane();
    tablaNumerosBingo = new javax.swing.JTable();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    jPanel1.setBackground(new java.awt.Color(204, 255, 255));

    textoConsultarCarton.setBackground(new java.awt.Color(0, 102, 102));
    textoConsultarCarton.setFont(new java.awt.Font("Bookman Old Style", 0, 48)); // NOI18N
    textoConsultarCarton.setForeground(new java.awt.Color(0, 102, 102));
    textoConsultarCarton.setText("Consultar Cartón");

    textoIdentificador.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
    textoIdentificador.setText("Identificador:");

    entradaIdentificador.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    entradaIdentificador.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        entradaIdentificadorActionPerformed(evt);
      }
    });

    botonRegresar.setBackground(new java.awt.Color(204, 204, 255));
    botonRegresar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    botonRegresar.setText("Regresar");
    botonRegresar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        botonRegresarActionPerformed(evt);
      }
    });

    botonMostrar.setBackground(new java.awt.Color(204, 204, 255));
    botonMostrar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    botonMostrar.setText("Mostrar");
    botonMostrar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        botonMostrarActionPerformed(evt);
      }
    });

    textoNombreJugador.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    textoNombreJugador.setText("Cartón asignado al jugador: ");

    tablaNumerosBingo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
    tablaNumerosBingo.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null, null},
        {null, null, null, null, null},
        {null, null, null, null, null},
        {null, null, null, null, null},
        {null, null, null, null, null}
      },
      new String [] {
        "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
      }
    ));
    tablaNumerosBingo.setEnabled(false);
    jScrollPane3.setViewportView(tablaNumerosBingo);

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(73, 73, 73)
            .addComponent(textoConsultarCarton))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(37, 37, 37)
            .addComponent(textoNombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(161, 161, 161)
            .addComponent(botonRegresar)
            .addGap(52, 52, 52)
            .addComponent(botonMostrar))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(100, 100, 100)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(textoIdentificador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entradaIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        .addContainerGap(47, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(textoConsultarCarton)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(textoIdentificador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(entradaIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(botonMostrar)
          .addComponent(botonRegresar))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(textoNombreJugador)
        .addGap(15, 15, 15))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void botonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarActionPerformed
    String identificador = entradaIdentificador.getText();
    if (identificador.length() == 0) {
      JOptionPane.showMessageDialog(this, "Porfavor ingrese el identificador del cartón deseado.",
              "Identificador vacío", JOptionPane.ERROR_MESSAGE);
      return;
    }
    // Se usa una expresión regular para determinar si el texto contiene algo además de números y letras
    if (!identificador.matches("[A-Za-z0-9]+")) {
      JOptionPane.showMessageDialog(this, "Porfavor ingrese un identificador de cartón válido.",
              "Identificador inválido", JOptionPane.ERROR_MESSAGE);
      return;
    }

    // Se busca en las listas de cartones, en la de cartones enviados
    // y los sin enviar, el código ingresado por el usuario.
    ArrayList<CartonBingo> cartonesGeneral = bingo.getCartones();
    cartonesGeneral.addAll(bingo.getCartonesGenerados());
    for (CartonBingo carton : cartonesGeneral) {
      if (identificador.equals(carton.getCodigoUnico())) {
        
        // Si el cartón ya fue asignado a algun jugador, se cambia
        // el texto de textoNombreJugador al nombre correspondiente
        if (carton.getDueño() != null) {
          textoNombreJugador.setText(carton.getDueño().getNombre());
        }
        
        TableModel modeloTabla = tablaNumerosBingo.getModel();
        // Se agregan los números del cartón a la tabla
        for (int i = 0; i < 5; i++) {
          for (int j = 0; j < 5; j++) {
            modeloTabla.setValueAt(carton.getNumeros()[i][j], i, j);
          }
        }
        return;
      }
    }

    JOptionPane.showMessageDialog(this, "No se encontró el cartón especificado.");
  }//GEN-LAST:event_botonMostrarActionPerformed

  private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
    this.dispose();
  }//GEN-LAST:event_botonRegresarActionPerformed

  private void entradaIdentificadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaIdentificadorActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_entradaIdentificadorActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(ConsultarCarton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(ConsultarCarton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(ConsultarCarton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(ConsultarCarton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton botonMostrar;
  private javax.swing.JButton botonRegresar;
  private javax.swing.JTextField entradaIdentificador;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane3;
  private javax.swing.JTable tablaNumerosBingo;
  private javax.swing.JLabel textoConsultarCarton;
  private javax.swing.JLabel textoIdentificador;
  private javax.swing.JLabel textoNombreJugador;
  // End of variables declaration//GEN-END:variables
}
