/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.bingo;

import javax.swing.JOptionPane;

/**
 * Ventana de envío de cartones.
 */
public class EnviarCarton extends javax.swing.JFrame {
  
  private Bingo bingo;
  
  /**
   * Constructor de la EnviarCarton.
   *
   * @param pBingo Objeto Bingo de la sesión actual.
   */
  public EnviarCarton(Bingo pBingo) {
    initComponents();
    bingo = pBingo;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel3 = new javax.swing.JPanel();
    textoEnviarCarton = new javax.swing.JLabel();
    textoCedula = new javax.swing.JLabel();
    textoCantidad = new javax.swing.JLabel();
    entradaCedula = new javax.swing.JTextField();
    botonEnviar = new javax.swing.JButton();
    botonRegresar = new javax.swing.JButton();
    entradaCantidad = new javax.swing.JSpinner();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    jPanel3.setBackground(new java.awt.Color(204, 255, 255));

    textoEnviarCarton.setFont(new java.awt.Font("Bookman Old Style", 0, 48)); // NOI18N
    textoEnviarCarton.setForeground(new java.awt.Color(0, 102, 102));
    textoEnviarCarton.setText("Enviar cartón a jugador");

    textoCedula.setFont(new java.awt.Font("Bookman Old Style", 0, 36)); // NOI18N
    textoCedula.setText("Cedula :");

    textoCantidad.setFont(new java.awt.Font("Bookman Old Style", 0, 36)); // NOI18N
    textoCantidad.setText("Cantidad :");

    entradaCedula.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
    entradaCedula.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        entradaCedulaActionPerformed(evt);
      }
    });

    botonEnviar.setBackground(new java.awt.Color(204, 204, 255));
    botonEnviar.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
    botonEnviar.setText("Enviar");
    botonEnviar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        botonEnviarActionPerformed(evt);
      }
    });

    botonRegresar.setBackground(new java.awt.Color(204, 204, 255));
    botonRegresar.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
    botonRegresar.setText("Regresar");
    botonRegresar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        botonRegresarActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addGap(197, 197, 197)
        .addComponent(textoCantidad)
        .addGap(18, 18, 18)
        .addComponent(entradaCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
            .addGap(80, 80, 80)
            .addComponent(botonRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botonEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(jPanel3Layout.createSequentialGroup()
            .addGap(62, 62, 62)
            .addComponent(textoCedula)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(entradaCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
          .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap(90, Short.MAX_VALUE)
            .addComponent(textoEnviarCarton)
            .addGap(12, 12, 12)))
        .addGap(59, 59, 59))
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addComponent(textoEnviarCarton)
        .addGap(33, 33, 33)
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(entradaCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(textoCedula))
        .addGap(35, 35, 35)
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(textoCantidad)
          .addComponent(entradaCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(31, 31, 31)
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(botonEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(botonRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(9, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void entradaCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaCedulaActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_entradaCedulaActionPerformed

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
      this.dispose();
    }//GEN-LAST:event_botonRegresarActionPerformed

  private void botonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEnviarActionPerformed
    String cedula = entradaCedula.getText();
    int cantidad = (int) entradaCantidad.getValue();
    String correoDestinatario = "";
    
    if (cedula.length() == 0) {
      JOptionPane.showMessageDialog(this, "Porfavor ingrese una cédula antes de continuar.",
                                    "Campo de cédula vacío", JOptionPane.ERROR_MESSAGE);
      return;
    }
    if (cantidad < 1 || cantidad > 5) {
      JOptionPane.showMessageDialog(this, "Porfavor ingrese una cantidad entre 1 y 5.",
                                    "Cantidad inválida", JOptionPane.ERROR_MESSAGE);
      return;
    }
    boolean cedulaEncontrada = false;
    for (Jugador jugador : bingo.getJugadores()) {
      if (jugador.getCedula().equals(cedula)) {
        cedulaEncontrada = true;
        correoDestinatario = jugador.getCorreo();
        break;
      }
    }
    if (!cedulaEncontrada) {
      JOptionPane.showMessageDialog(this, "No se encontró un jugador con la cédula ingresada.",
                                    "Cédula no reconocida", JOptionPane.ERROR_MESSAGE);
      return;
    }
    if (bingo.getCartonesGenerados().size() < cantidad) {
      JOptionPane.showMessageDialog(this, "No hay suficientes cartones para enviar.",
                                    "Cartones insuficientes", JOptionPane.ERROR_MESSAGE);
      return;
    }
    bingo.enviarCorreo(correoDestinatario, cantidad);
    JOptionPane.showMessageDialog(this, "Cartones enviados satisfactoriamente.");
  }//GEN-LAST:event_botonEnviarActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(EnviarCarton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(EnviarCarton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(EnviarCarton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(EnviarCarton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton botonEnviar;
  private javax.swing.JButton botonRegresar;
  private javax.swing.JSpinner entradaCantidad;
  private javax.swing.JTextField entradaCedula;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JLabel textoCantidad;
  private javax.swing.JLabel textoCedula;
  private javax.swing.JLabel textoEnviarCarton;
  // End of variables declaration//GEN-END:variables
}
