/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.bingo;

import javax.swing.JOptionPane;

/**
 * Ventana de juego.
 */
public class IniciarJuego extends javax.swing.JFrame {

  private Bingo bingo;

  /**
   * Constructor de la clase IniciarJuego
   *
   * @param pBingo Objeto Bingo con los datos de la sesión actual.
   */
  public IniciarJuego(Bingo pBingo) {
    initComponents();
    bingo = pBingo;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel4 = new javax.swing.JPanel();
    opcionesConfiguracion = new javax.swing.JComboBox<>();
    textoConfiguracion = new javax.swing.JLabel();
    textoPremio = new javax.swing.JLabel();
    entradaPremio = new javax.swing.JTextField();
    textoIniciarJuego = new javax.swing.JLabel();
    botonIniciar = new javax.swing.JButton();
    botonRegresar = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    jPanel4.setBackground(new java.awt.Color(204, 255, 255));

    opcionesConfiguracion.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
    opcionesConfiguracion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "En X", "4 esquinas", "Cartón lleno", "En Z", "" }));
    opcionesConfiguracion.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        opcionesConfiguracionActionPerformed(evt);
      }
    });

    textoConfiguracion.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
    textoConfiguracion.setText("Configuración :");
    textoConfiguracion.setToolTipText("");

    textoPremio.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
    textoPremio.setText("Premio :");

    entradaPremio.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
    entradaPremio.setHorizontalAlignment(javax.swing.JTextField.CENTER);

    textoIniciarJuego.setFont(new java.awt.Font("Bookman Old Style", 0, 48)); // NOI18N
    textoIniciarJuego.setForeground(new java.awt.Color(0, 102, 102));
    textoIniciarJuego.setText("Iniciar juego ");

    botonIniciar.setBackground(new java.awt.Color(204, 204, 255));
    botonIniciar.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
    botonIniciar.setText("Iniciar");
    botonIniciar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        botonIniciarActionPerformed(evt);
      }
    });

    botonRegresar.setBackground(new java.awt.Color(204, 204, 255));
    botonRegresar.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
    botonRegresar.setText("Regresar");
    botonRegresar.setToolTipText("");
    botonRegresar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        botonRegresarActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel4Layout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addComponent(textoIniciarJuego)
        .addGap(197, 197, 197))
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(textoConfiguracion)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(opcionesConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(textoPremio)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(entradaPremio)
        .addGap(19, 19, 19))
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
        .addGap(163, 163, 163)
        .addComponent(botonRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(145, 145, 145)
        .addComponent(botonIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(174, Short.MAX_VALUE))
    );
    jPanel4Layout.setVerticalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel4Layout.createSequentialGroup()
        .addComponent(textoIniciarJuego)
        .addGap(42, 42, 42)
        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(textoConfiguracion)
          .addComponent(opcionesConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(textoPremio)
          .addComponent(entradaPremio, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(botonIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(botonRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(27, 27, 27))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void opcionesConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionesConfiguracionActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_opcionesConfiguracionActionPerformed

  private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
    this.dispose();
  }//GEN-LAST:event_botonRegresarActionPerformed

  private void botonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIniciarActionPerformed
    String configuracionJuego = (String) opcionesConfiguracion.getSelectedItem();
    String premio = entradaPremio.getText();

    if (premio.length() == 0) {
      JOptionPane.showMessageDialog(this, "Porfavor ingrese el premio antes de continuar",
              "Premio no establecido", JOptionPane.ERROR_MESSAGE);
      return;
    }
    if (bingo.getCartones().isEmpty()) {
      JOptionPane.showMessageDialog(this, "Porfavor cree y envíe los cartones antes de continuar",
              "Sin cartones disponibles", JOptionPane.ERROR_MESSAGE);
      return;
    }
    
    bingo.setModoJuego(configuracionJuego);
    bingo.setPremio(premio);
    CantarNumero ventanaCantarNumero = new CantarNumero(bingo);
    ventanaCantarNumero.setVisible(true);
    
  }//GEN-LAST:event_botonIniciarActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(IniciarJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(IniciarJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(IniciarJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(IniciarJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton botonIniciar;
  private javax.swing.JButton botonRegresar;
  private javax.swing.JTextField entradaPremio;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JComboBox<String> opcionesConfiguracion;
  private javax.swing.JLabel textoConfiguracion;
  private javax.swing.JLabel textoIniciarJuego;
  private javax.swing.JLabel textoPremio;
  // End of variables declaration//GEN-END:variables
}
