/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.bingo;

import javax.swing.JOptionPane;

/**
 * Ventana de registro de jugador.
 */
public class RegistrarJugador extends javax.swing.JFrame {

  private Bingo bingo;

  /**
   * Constructor de la clase RegistrarJugador.
   *
   * @param pBingo Objeto Bingo de la sesión actual.
   */
  public RegistrarJugador(Bingo pBingo) {
    initComponents();
    bingo = pBingo;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        textoRegistrarJugador = new javax.swing.JLabel();
        entradaNombre = new javax.swing.JTextField();
        entradaCedula = new javax.swing.JTextField();
        entradaCorreo = new javax.swing.JTextField();
        botonSalir = new javax.swing.JButton();
        botonGuardar = new javax.swing.JButton();
        textoNombre = new javax.swing.JLabel();
        textoCedula = new javax.swing.JLabel();
        textoCorreo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        textoRegistrarJugador.setBackground(new java.awt.Color(0, 102, 102));
        textoRegistrarJugador.setFont(new java.awt.Font("Bookman Old Style", 0, 48)); // NOI18N
        textoRegistrarJugador.setForeground(new java.awt.Color(0, 102, 102));
        textoRegistrarJugador.setText("Registrar jugador");

        entradaNombre.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        entradaCedula.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        entradaCorreo.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        botonSalir.setBackground(new java.awt.Color(204, 204, 255));
        botonSalir.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        botonSalir.setText("Regresar");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        botonGuardar.setBackground(new java.awt.Color(204, 204, 255));
        botonGuardar.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        botonGuardar.setText("Guardar");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        textoNombre.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        textoNombre.setText("Nombre :");

        textoCedula.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        textoCedula.setText("Cedula :");

        textoCorreo.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        textoCorreo.setText("Correo :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textoCedula)
                .addGap(18, 18, 18)
                .addComponent(entradaCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 196, Short.MAX_VALUE)
                .addComponent(textoCorreo)
                .addGap(18, 18, 18)
                .addComponent(entradaCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(textoNombre)
                        .addGap(18, 18, 18)
                        .addComponent(entradaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(textoRegistrarJugador)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoRegistrarJugador)
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entradaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoNombre))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entradaCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoCedula))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entradaCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoCorreo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
    String nombre = entradaNombre.getText();
    String cedula = entradaCedula.getText();
    String correo = entradaCorreo.getText();

    if (nombre.length() == 0) {
      JOptionPane.showMessageDialog(this, "El nombre no puede quedar vacío.",
              "Error en el nombre elegido", JOptionPane.ERROR_MESSAGE);
      return;
    }
    if (nombre.length() > 50) {
      JOptionPane.showMessageDialog(this, "El nombre no puede contener más de 50 caracteres.",
              "Error en el nombre elegido", JOptionPane.ERROR_MESSAGE);
      return;
    }
    for (Jugador jugador : bingo.getJugadores()) {
      if (jugador.getCedula().equals(cedula)) {
        JOptionPane.showMessageDialog(this, "Ya hay un jugador registrado con la cédula introducida.",
                "Cédula ya en uso", JOptionPane.ERROR_MESSAGE);
        return;
      }
    }
    if (cedula.length() != 7) {
      JOptionPane.showMessageDialog(this, "La cédula debe tener exactamente 7 números.",
              "Cédula inválida", JOptionPane.ERROR_MESSAGE);
      return;
    }
    if (!correo.contains("@")) { // correo inválido
      JOptionPane.showMessageDialog(this, "El correo electrónico introducido es inválido.",
              "Correo electrónico inválido", JOptionPane.ERROR_MESSAGE);
      return;
    }

    bingo.registrarJugador(nombre, cedula, correo);
    bingo.guardarJugadoresEnCSV();
    JOptionPane.showMessageDialog(this, "Jugador registrado exitosamente.");

  }//GEN-LAST:event_botonGuardarActionPerformed

  private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
    this.dispose();
  }//GEN-LAST:event_botonSalirActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(RegistrarJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(RegistrarJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(RegistrarJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(RegistrarJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JTextField entradaCedula;
    private javax.swing.JTextField entradaCorreo;
    private javax.swing.JTextField entradaNombre;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel textoCedula;
    private javax.swing.JLabel textoCorreo;
    private javax.swing.JLabel textoNombre;
    private javax.swing.JLabel textoRegistrarJugador;
    // End of variables declaration//GEN-END:variables
}
